
services:
  postgres:
    image: postgres:16-alpine
    container_name: stocksense_db
    environment:
      POSTGRES_USER: stocksense
      POSTGRES_PASSWORD: stocksense_pass
      POSTGRES_DB: stocksense
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stocksense -d stocksense"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
